# @package _global_

# Remove Hydra logging

defaults:
  - _self_
  - override /hydra/hydra_logging: disabled
  - override /hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
